algo: dueldqn
gamma: 0.99
batch_size: 256
target_update_freq: 10
epsilon: 0.1
buffer_size: 8_000

QNet:
  net_arch: [100]
  activation_fn: ReLU
  optimizer: Adam
  lr: !!float 3e-4
  v_head: [100]
  adv_head: [100]
  mix_type: max