algo: sac
gamma: 0.99
batch_size: 256
warmup_steps: 10_000
env_steps: 1
buffer_size: 1000_000

actor:
  net_arch: [256, 256]
  activation_fn: ReLU
  state_std_independent: False
  optimizer: Adam
  lr: !!float 3e-4

critic:
  net_arch: [256, 256]
  activation_fn: ReLU
  optimizer: Adam
  lr: !!float 3e-4
  tau: 0.05

log_alpha:
  auto_tune: True
  init_value: 0.0
  optimizer: Adam
  lr: !!float 3e-4
