algo: td3
gamma: 0.99
batch_size: 256
sigma: 0.2
c: 0.5
policy_freq: 2
warmup_steps: 10_000
env_steps: 1
buffer_size: 1000_000

actor:
  net_arch: [256, 256]
  activation_fn: ReLU
  optimizer: Adam
  lr: !!float 3e-4
  tau: 0.05
  
critic:
  net_arch: [256, 256]
  activation_fn: ReLU
  optimizer: Adam
  lr: !!float 3e-4
  tau: 0.05
