algo: dagger_continuous
batch_size: 256

buffer_size: -1

expert:
  config: conf/agent/rl/sac.yaml
  model_path: data/hopper-v4_sac.pt

actor:
  net_arch: [256, 256]
  activation_fn: ReLU
  state_std_independent: False
  optimizer: Adam
  lr: !!float 3e-4